# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/MultiCircleCPUcopy/MultiCircleCPU.cache/wt [current_project]
set_property parent.project_path E:/MultiCircleCPUcopy/MultiCircleCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/SegLED.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/Select_32.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/SaveReg.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/RegFile.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/PC.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/LEDdisplay.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/IR.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/InsMem.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/Extend.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/DataMEM.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/ControlUnit.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/ALU.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/PC_Control.v
  E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/sources_1/new/MultiCircleCPU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/constrs_1/new/MultiCircleCPU.xdc
set_property used_in_implementation false [get_files E:/MultiCircleCPUcopy/MultiCircleCPU.srcs/constrs_1/new/MultiCircleCPU.xdc]


synth_design -top MultiCircleCPU -part xc7a35tcpg236-1


write_checkpoint -force -noxdef MultiCircleCPU.dcp

catch { report_utilization -file MultiCircleCPU_utilization_synth.rpt -pb MultiCircleCPU_utilization_synth.pb }
